import test from 'node:test';import assert from 'node:assert/strict';import {defaults,themes,scenePrompt,shareText,localDay,escapeHTML} from '../core.js';import {createApp} from '../server.js';
test('scene prompt uses taste and explicit theme only',()=>{const p=scenePrompt('Boundaries',defaults);assert.match(p,/dining room/);assert.match(p,/grainy analog/);assert.doesNotMatch(p,/birth|journal/);});
test('sharing excludes private fields',()=>{const text=shareText({title:'Piece',line:'Line',note:'SECRET NOTE',response:'SECRET RESPONSE',prompt:'SECRET PROMPT'});assert.doesNotMatch(text,/SECRET/);});
test('safe user content and local dates',()=>{assert.equal(escapeHTML('<img onerror="x">'),'&lt;img onerror=&quot;x&quot;&gt;');assert.equal(localDay(new Date(2026,8,8,23)), '2026-09-08');assert.equal(Object.keys(themes).length,4);});
async function withServer(options,run){const server=createApp(options);await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`;try{await run(origin);}finally{await new Promise(r=>server.close(r));}}
test('unconfigured service is explicit and secrets are not served',async()=>withServer({key:''},async origin=>{assert.deepEqual(await (await fetch(origin+'/api/status')).json(),{configured:false});assert.equal((await fetch(origin+'/.env')).status,404);assert.equal((await fetch(origin+'/server.js')).status,404);const r=await fetch(origin+'/api/generate',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify({prompt:'room'})});assert.equal(r.status,503);}));
test('generation sends only approved prompt and returns image',async()=>{let sent;await withServer({key:'test-key',providerFetch:async(url,opts)=>{sent=JSON.parse(opts.body);return Response.json({data:[{b64_json:'YWJj'}]});}},async origin=>{const r=await fetch(origin+'/api/generate',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify({prompt:'One red chair'})});assert.equal(r.status,200);assert.equal((await r.json()).image,'data:image/png;base64,YWJj');assert.equal(sent.prompt,'One red chair');assert.equal(Object.hasOwn(sent,'note'),false);});});
test('rejects cross-origin, extra private fields and oversized prompts',async()=>withServer({key:'test-key'},async origin=>{const send=(data,from=origin)=>fetch(origin+'/api/generate',{method:'POST',headers:{Origin:from,'Content-Type':'application/json'},body:JSON.stringify(data)});assert.equal((await send({prompt:'room'},'https://evil.example')).status,403);assert.equal((await send({prompt:'room',note:'private'})).status,400);assert.equal((await send({prompt:'a'.repeat(2501)})).status,400);}));
test('provider errors do not disclose credentials or raw errors',async()=>withServer({key:'SECRET',providerFetch:async()=>new Response('SECRET',{status:401})},async origin=>{const r=await fetch(origin+'/api/generate',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify({prompt:'room'})});assert.equal(r.status,502);assert.doesNotMatch(await r.text(),/SECRET/);}));
