import test from 'node:test';import assert from 'node:assert/strict';import {createStudioServer,imageBytes} from '../server.mjs';
const UID='11111111-1111-4111-8111-111111111111',RID='22222222-2222-4222-8222-222222222222';
const PNG='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jYwAAAABJRU5ErkJggg==';
const env={ENABLE_AI:'1',OPENAI_API_KEY:'test-provider-secret',IW_GATEWAY_TOKEN:'test-gateway-secret',SUPABASE_URL:'https://db.example',SUPABASE_PUBLISHABLE_KEY:'public-key',APP_ORIGIN:'https://studio.example'};
const headers={'Content-Type':'application/json',Authorization:'Bearer user-test',Origin:env.APP_ORIGIN};const json=(d,status=200)=>new Response(JSON.stringify(d),{status,headers:{'Content-Type':'application/json'}});
async function run(fn,{member=false,quota=true,providerError=false,billingReady=false,envOverride={}}={}){const calls=[];const seen=new Set();const provider=async(url,o)=>{calls.push({url,options:o});if(url.endsWith('/auth/v1/user'))return o.headers.Authorization==='Bearer user-test'?json({id:UID,email:'test@example.invalid'}):json({},401);if(url.includes('/functions/')){const b=JSON.parse(o.body);if(b.action==='billing_ready')return json({ready:billingReady});if(b.action==='member')return json({member,subscription:member?{plan:'monthly',status:'active'}:null});if(b.action==='quota'){if(seen.has(b.requestId))return json({error:'Duplicate request'},409);seen.add(b.requestId);return quota?json({allowed:true,used:1,limit:1}):json({error:'Daily limit'},429);}if(b.action==='shared_prompt')return json({prompt:'Two bowls on a table.'});if(b.action==='shared_finish')return json({id:RID});if(b.action==='share')return json({title:'Shared',line:'Public',image:PNG});}
if(providerError)return json({error:{code:'test_secret_would_leak'}},401);if(url.endsWith('/responses'))return json({output:[{content:[{type:'output_text',text:JSON.stringify({title:'Begin',line:'An opening.',reflection:'A possible interpretation.',invitation:'What do you see?',visual_concept:'A red chair beside a doorway.',why_this:'Your chosen theme.'})}]}]});if(url.includes('/images/'))return json({data:[{b64_json:PNG.split(',')[1]}]});throw Error('Unexpected test request '+url);};const {server}=createStudioServer({env:{...env,...envOverride},provider});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;try{await fn(base,calls)}finally{server.closeAllConnections();await new Promise(r=>server.close(r));}}
const post=(base,path,b,h=headers)=>fetch(base+path,{method:'POST',headers:h,body:JSON.stringify(b)});
test('static files work; source and secrets denied',async()=>run(async(base)=>{assert.equal((await fetch(base)).status,200);for(const p of ['/.env','/server.mjs','/tests/release-server.test.mjs','/%2e%2e/.env'])assert.equal((await fetch(base+p)).status,404);const cfg=await(await fetch(base+'/api/config')).text();assert.ok(!cfg.includes('test-provider-secret'));assert.ok(!cfg.includes('test-gateway-secret'));assert.equal(JSON.parse(cfg).checkoutEnabled,false);}));
test('unauthenticated and foreign origin calls rejected',async()=>run(async base=>{assert.equal((await post(base,'/api/generate',{}, {'Content-Type':'application/json'})).status,401);assert.equal((await post(base,'/api/generate',{}, {...headers,Origin:'https://evil.example'})).status,403);}));
test('bad consent, malformed JSON and oversized input rejected',async()=>run(async(base,calls)=>{assert.equal((await post(base,'/api/generate',{consent:'yes',requestId:RID,prompt:'A red chair.'})).status,400);assert.equal((await fetch(base+'/api/interpret',{method:'POST',headers,body:'{bad'})).status,400);assert.equal((await post(base,'/api/interpret',{consent:true,requestId:RID,theme:'rest',experience:'x'.repeat(26000)})).status,413);assert.equal(calls.filter(c=>c.url.includes('openai')).length,0);}));
test('duplicate ID prevents second provider call',async()=>run(async(base,calls)=>{const body={requestId:RID,consent:true,prompt:'A sculptural chair beside a window.'};assert.equal((await post(base,'/api/generate',body)).status,200);assert.equal((await post(base,'/api/generate',body)).status,409);assert.equal(calls.filter(c=>c.url.includes('/images/')).length,1);}));
test('quota denial never runs a paid image request',async()=>run(async(base,calls)=>{assert.equal((await post(base,'/api/generate',{requestId:RID,consent:true,prompt:'A quiet red chair.'})).status,429);assert.equal(calls.filter(c=>c.url.includes('/images/')).length,0);},{quota:false}));
test('reflection strips private fields and raw birth details',async()=>run(async(base,calls)=>{const r=await post(base,'/api/interpret',{requestId:RID,consent:true,theme:'rest',experience:'Chosen words',mood:'quiet',private_note:'SECRET_JOURNAL',astrology:{birthISO:'PRIVATE_BIRTH',natal:[{name:'Sun',sign:'Aries',degree:5}],untrusted:'HIDDEN'}});assert.equal(r.status,200);const sent=JSON.parse(calls.find(c=>c.url.endsWith('/responses')).options.body);assert.equal(sent.store,false);assert.ok(!JSON.stringify(sent).includes('SECRET_JOURNAL'));assert.ok(!JSON.stringify(sent).includes('PRIVATE_BIRTH'));assert.ok(JSON.stringify(sent).includes('Chosen words'));}));
test('reference editing uses multipart and exact approved prompt',async()=>run(async(base,calls)=>{const prompt='Exactly this approved visual prompt.';assert.equal((await post(base,'/api/generate',{requestId:RID,consent:true,prompt,references:[PNG]})).status,200);const sent=calls.find(c=>c.url.endsWith('/edits'));assert.ok(sent.options.body instanceof FormData);assert.equal(sent.options.body.get('prompt'),prompt);assert.equal(sent.options.body.getAll('image[]').length,1);}));
test('print resolution is server gated',async()=>run(async(base,calls)=>{assert.equal((await post(base,'/api/generate',{requestId:RID,consent:true,prompt:'A large red chair.',highResolution:true})).status,403);assert.equal(calls.filter(c=>c.url.includes('/images/')).length,0);}));
test('PNG signatures checked and provider errors redacted',async()=>{assert.throws(()=>imageBytes('data:image/png;base64,'+Buffer.from('not really an image').toString('base64')));await run(async(base)=>{const r=await post(base,'/api/generate',{requestId:RID,consent:true,prompt:'A quiet red chair.'});assert.equal(r.status,502);const s=await r.text();assert.ok(!s.includes('test_secret_would_leak'));assert.ok(!s.includes('test-provider-secret'));},{providerError:true});});

const billingEnv={BILLING_LAUNCH_READY:'1',STRIPE_PORTAL_URL:'https://billing.stripe.com/p/login/sample',STRIPE_MONTHLY_PAYMENT_LINK:'https://buy.stripe.com/sample'};
test('checkout stays disabled when the live Stripe connection is not ready',async()=>run(async base=>{
 const cfg=await(await fetch(base+'/api/config')).json();assert.equal(cfg.checkoutEnabled,false);
 assert.equal((await post(base,'/api/checkout',{cadence:'monthly'})).status,503);
},{envOverride:billingEnv}));
test('verified checkout links the authenticated account and existing members use their portal',async()=>{
 await run(async base=>{const response=await post(base,'/api/checkout',{cadence:'monthly'});assert.equal(response.status,200);const url=new URL((await response.json()).url);assert.equal(url.searchParams.get('client_reference_id'),UID);assert.equal(url.searchParams.get('locked_prefilled_email'),'test@example.invalid');},{billingReady:true,envOverride:billingEnv});
 await run(async base=>{assert.equal((await post(base,'/api/checkout',{cadence:'monthly'})).status,409);},{billingReady:true,member:true,envOverride:billingEnv});
});
