import * as Astronomy from 'astronomy-engine';

const BODIES=[['Sun',Astronomy.Body.Sun],['Moon',Astronomy.Body.Moon],['Mercury',Astronomy.Body.Mercury],['Venus',Astronomy.Body.Venus],['Mars',Astronomy.Body.Mars],['Jupiter',Astronomy.Body.Jupiter],['Saturn',Astronomy.Body.Saturn],['Uranus',Astronomy.Body.Uranus],['Neptune',Astronomy.Body.Neptune],['Pluto',Astronomy.Body.Pluto]];
const SIGNS=['Aries','Taurus','Gemini','Cancer','Leo','Virgo','Libra','Scorpio','Sagittarius','Capricorn','Aquarius','Pisces'];
const ASPECTS=[['conjunction',0,8],['sextile',60,5],['square',90,6],['trine',120,6],['opposition',180,8]];
const norm=x=>((x%360)+360)%360;
const rad=x=>x*Math.PI/180,deg=x=>x*180/Math.PI;
const separation=(a,b)=>{const d=Math.abs(norm(a)-norm(b));return Math.min(d,360-d)};
function ecliptic(body,date){const eq=Astronomy.Equator(body,date,Astronomy.Body.Earth,true,true);const ec=Astronomy.Ecliptic(eq.vec);return norm(ec.elon)}
function point(name,longitude){const lon=norm(longitude),signIndex=Math.floor(lon/30);return{name,longitude:+lon.toFixed(4),sign:SIGNS[signIndex],degree:+(lon%30).toFixed(2)}}
function julianDate(date){return date.getTime()/86400000+2440587.5}
function ascendant(date,lat,lng){const jd=julianDate(date),t=(jd-2451545)/36525;let gst=280.46061837+360.98564736629*(jd-2451545)+0.000387933*t*t-t*t*t/38710000;const lst=rad(norm(gst+lng)),phi=rad(lat),eps=rad(23.439291-0.0130042*t);const lambda=norm(deg(Math.atan2(-Math.cos(lst),Math.sin(lst)*Math.cos(eps)+Math.tan(phi)*Math.sin(eps))));return point('Ascendant',lambda)}
function wholeSignHouses(asc,natal){const rising=Math.floor(asc.longitude/30);return Array.from({length:12},(_,i)=>{const signIndex=(rising+i)%12;return{house:i+1,sign:SIGNS[signIndex],startLongitude:signIndex*30,planets:natal.filter(p=>Math.floor(p.longitude/30)===signIndex).map(p=>p.name)}})}
export function positions(date){return BODIES.map(([name,body])=>point(name,ecliptic(body,date)))}
export function aspects(points){const out=[];for(let i=0;i<points.length;i++)for(let j=i+1;j<points.length;j++){const sep=separation(points[i].longitude,points[j].longitude);for(const[name,angle,orb]of ASPECTS){const delta=Math.abs(sep-angle);if(delta<=orb){out.push({a:points[i].name,b:points[j].name,type:name,orb:+delta.toFixed(2)});break}}}return out.sort((a,b)=>a.orb-b.orb)}
export function transitAspects(natal,current){const out=[];for(const t of current)for(const n of natal){const sep=separation(t.longitude,n.longitude);for(const[name,angle,orb]of ASPECTS){const delta=Math.abs(sep-angle);if(delta<=Math.min(orb,4)){out.push({transit:t.name,natal:n.name,type:name,orb:+delta.toFixed(2)});break}}}return out.sort((a,b)=>a.orb-b.orb).slice(0,12)}
export function calculateChart({birthISO,atISO,lat,lng}){const birth=new Date(birthISO),at=atISO?new Date(atISO):new Date();if(!Number.isFinite(birth.getTime())||!Number.isFinite(at.getTime()))throw new Error('Invalid date.');const natal=positions(birth),current=positions(at);let rising=null,houses=null;if(Number.isFinite(+lat)&&Number.isFinite(+lng)&&+lat>=-90&&+lat<=90&&+lng>=-180&&+lng<=180){rising=ascendant(birth,+lat,+lng);houses=wholeSignHouses(rising,natal)}return{system:'tropical-geocentric',houseSystem:houses?'whole-sign':null,birthISO:birth.toISOString(),atISO:at.toISOString(),location:rising?{lat:+lat,lng:+lng}:null,ascendant:rising,houses,natal,natalAspects:aspects(natal).slice(0,16),transits:current,transitAspects:transitAspects(natal,current),notice:'Astrology is used as an optional symbolic reflection lens, not a factual prediction or diagnosis.'}}
