/* Authenticated requests and content-addressed private artwork storage. */
(function(g){'use strict';const SK='innerworld-supabase-session-v1';let cfg,session=null,refreshing;const readSession=()=>{try{return JSON.parse(localStorage.getItem(SK)||'null')}catch{return null}};session=readSession();const keep=s=>{session=s;s?localStorage.setItem(SK,JSON.stringify(s)):localStorage.removeItem(SK);};g.addEventListener('storage',e=>{if(e.key===SK)session=readSession();});
async function json(r){if(r.status===204)return null;let d;try{d=await r.json()}catch{throw Error('Unreadable service response.')}if(!r.ok){const e=Error(d.error_description||d.msg||d.message||d.error||'Service request failed.');e.status=r.status;e.code=d.code;throw e;}return d;}
async function init(){cfg=await json(await fetch('./api/config',{cache:'no-store',signal:AbortSignal.timeout(8000)}));const h=new URLSearchParams(location.hash.slice(1));if(h.has('error')){history.replaceState(null,'',location.pathname+'#today');throw Error('This sign-in link has expired or was already used. Request a fresh sign-in email.');}if(h.has('access_token')){const s={access_token:h.get('access_token'),refresh_token:h.get('refresh_token'),expires_at:Date.now()/1000+(+h.get('expires_in')||3600)};history.replaceState(null,'',location.pathname);if(!s.refresh_token)throw Error('Incomplete sign-in link.');await json(await fetch(cfg.supabaseUrl+'/auth/v1/user',{headers:{apikey:cfg.supabaseKey,Authorization:'Bearer '+s.access_token},signal:AbortSignal.timeout(15000)}));keep(s);const back=sessionStorage.getItem('iw-return');location.hash=/^#between-invite\/[a-f0-9]{48}$/.test(back||'')?back:'#today';sessionStorage.removeItem('iw-return');}return cfg;}
async function refresh(){if(refreshing)return refreshing;if(!session?.refresh_token)return;const before=session.access_token;const run=async()=>{session=readSession();if(!session?.refresh_token||session.access_token!==before)return;const r=await fetch(cfg.supabaseUrl+'/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:{apikey:cfg.supabaseKey,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:session.refresh_token}),signal:AbortSignal.timeout(15000)});if([400,401].includes(r.status)){keep(null);return;}const s=await json(r);s.expires_at=Date.now()/1000+s.expires_in;keep(s);};refreshing=(navigator.locks?navigator.locks.request('innerworld-auth-refresh',run):run()).finally(()=>refreshing=null);return refreshing;}
async function token(){if(session?.expires_at<Date.now()/1000+60)await refresh();return session?.access_token;}
async function req(path,{method='GET',body,headers={},auth=true,raw=false,retry=true}={}){if(!cfg?.supabaseUrl)throw Error('Cloud is unavailable. Local mode still works.');const t=auth?await token():null;if(auth&&!t)throw Object.assign(Error('Sign in first.'),{status:401});const r=await fetch(cfg.supabaseUrl+path,{method,headers:{apikey:cfg.supabaseKey,...(t?{Authorization:'Bearer '+t}:{}),...(body!==undefined&&!raw?{'Content-Type':'application/json'}:{}),...headers},body:body===undefined?undefined:raw?body:JSON.stringify(body),signal:AbortSignal.timeout(45000)});if(r.status===401&&retry&&auth){await refresh();if(session)return req(path,{method,body,headers,auth,raw,retry:false});}if(raw){if(!r.ok)await json(r);return r;}return json(r);}
async function me(){if(!session)return null;try{return await req('/auth/v1/user')}catch(e){if(e.status===401){keep(null);return null}throw e;}}
const rpc=(n,b={})=>req('/rest/v1/rpc/'+n,{method:'POST',body:b});
async function api(path,b={},auth=true,retry=true){const t=auth?await token():null;if(auth&&!t)throw Object.assign(Error('Sign in first.'),{status:401});const r=await fetch('.'+path,{method:'POST',headers:{'Content-Type':'application/json',...(t?{Authorization:'Bearer '+t}:{})},body:JSON.stringify(b),signal:AbortSignal.timeout(175000)});if(r.status===401&&auth&&retry){await refresh();if(session)return api(path,b,auth,false);}return json(r);}
async function send(email){if(/^#between-invite\/[a-f0-9]{48}$/.test(location.hash))sessionStorage.setItem('iw-return',location.hash);return req('/auth/v1/otp?redirect_to='+encodeURIComponent(location.origin+location.pathname),{method:'POST',auth:false,body:{email:email.trim(),create_user:true}});}
async function verify(email,code){const s=await req('/auth/v1/verify',{method:'POST',auth:false,body:{email:email.trim(),token:code.trim(),type:'email'}});s.expires_at=Date.now()/1000+s.expires_in;keep(s);}
async function signOut(){try{if(session)await req('/auth/v1/logout',{method:'POST'})}finally{keep(null)}}
function imageBlob(uri){if(!InnerworldCore.safeImage(uri))throw Error('Unsupported artwork.');const [h,b]=uri.split(',');return new Blob([Uint8Array.from(atob(b),c=>c.charCodeAt(0))],{type:h.slice(5,-7)});}
async function upload(uri,uid,folder='pieces'){const b=imageBlob(uri);if(b.size>12000000)throw Error('Artwork exceeds 12 MB.');const hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',await b.arrayBuffer()))].map(n=>n.toString(16).padStart(2,'0')).join(''),ext={'image/png':'png','image/jpeg':'jpg','image/webp':'webp'}[b.type],path=`${uid}/${folder}/${hash}.${ext}`;try{await req('/storage/v1/object/innerworld-private/'+path,{method:'POST',body:b,raw:true,headers:{'Content-Type':b.type,'x-upsert':'false'}})}catch(e){if(e.status!==409&&!/already exists|Duplicate/i.test(e.message))throw e;}return path;}
async function image(path){const r=await req('/storage/v1/object/authenticated/innerworld-private/'+path,{raw:true}),b=await r.blob();if(b.size>12000000||!['image/png','image/jpeg','image/webp'].includes(b.type))throw Error('Unsupported cloud artwork.');return new Promise((yes,no)=>{const f=new FileReader();f.onload=()=>yes(f.result);f.onerror=()=>no(Error('Image read failed'));f.readAsDataURL(b)});}
async function push(local){const u=await me();if(!u)throw Error('Sign in first.');if(local.owner&&local.owner!==u.id)throw Error('This studio belongs to another cloud account.');const s=structuredClone(local);for(const p of [...s.pieces,...(s.draft?[s.draft]:[])])if(p.image)p.imagePath=await upload(p.image,u.id);for(const r of s.profile?.references||[])if(r.image)r.imagePath=await upload(r.image,u.id,'references');const d=structuredClone(s);for(const p of [...d.pieces,...(d.draft?[d.draft]:[])])delete p.image;for(const r of d.profile?.references||[])delete r.image;delete d.owner;delete d.revision;try{s.revision=Number(await rpc('iw_save_studio',{p_document:d,p_revision:local.revision||0}));}catch(e){if(['40001','PT409'].includes(e.code)||/CLOUD_CONFLICT/.test(e.message))throw Error('A newer cloud version exists. Download it before uploading; local changes remain intact.');throw e;}s.owner=u.id;return s;}
async function pull(){const u=await me();if(!u)throw Error('Sign in first.');const rows=await req('/rest/v1/iw_studio_snapshots?select=revision,document&user_id=eq.'+u.id);if(!rows.length)throw Error('No cloud snapshot exists. Upload this device first.');const s=rows[0].document;for(const p of [...s.pieces,...(s.draft?[s.draft]:[])])if(p.imagePath){if(!p.imagePath.startsWith(u.id+'/'))throw Error('Artwork ownership mismatch.');p.image=await image(p.imagePath);}for(const r of s.profile?.references||[])if(r.imagePath){if(!r.imagePath.startsWith(u.id+'/'))throw Error('Reference ownership mismatch.');r.image=await image(r.imagePath);}s.revision=Number(rows[0].revision);s.owner=u.id;return s;}
g.IWClient={init,config:()=>cfg,me,rpc,api,send,verify,signOut,push,pull,upload,image,imageBlob,shares:()=>req('/rest/v1/iw_share_cards?select=id,title,expires_at,revoked_at&order=created_at.desc&limit=200'),notices:()=>req('/rest/v1/iw_notifications?select=id,title,body,read_at&order=created_at.desc&limit=50'),readNotice:id=>req('/rest/v1/iw_notifications?id=eq.'+encodeURIComponent(id),{method:'PATCH',body:{read_at:new Date().toISOString()}})};
})(globalThis);
