/* INNERWORLD cloud account layer. Supabase publishable key is intentionally public; RLS protects private rows. */
'use strict';
(()=>{
const URL='https://jefhxrtaqzxcijzvzpcy.supabase.co';
const KEY='sb_publishable_TXROosbWqu-nUB0lkGGKmw_7vr0eP4r';
const SESSION_KEY='innerworld-supabase-session-v1';
let session=null;
try{session=JSON.parse(localStorage.getItem(SESSION_KEY)||'null')}catch{}
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,{method='GET',body,auth=true,headers={}}={}){
 const h={apikey:KEY,...headers}; if(body!==undefined)h['Content-Type']='application/json'; if(auth&&session?.access_token)h.Authorization='Bearer '+session.access_token;
 const r=await fetch(URL+path,{method,headers:h,body:body===undefined?undefined:JSON.stringify(body)}); const text=await r.text(); let data=null; try{data=text?JSON.parse(text):null}catch{data=text}
 if(!r.ok)throw Error(data?.msg||data?.message||data?.error_description||data?.error||`Cloud request failed (${r.status}).`); return data;
}
function saveSession(s){session=s||null;if(session)localStorage.setItem(SESSION_KEY,JSON.stringify(session));else localStorage.removeItem(SESSION_KEY)}
async function refresh(){if(!session?.refresh_token)return null;try{const next=await api('/auth/v1/token?grant_type=refresh_token',{method:'POST',body:{refresh_token:session.refresh_token},auth:false});saveSession(next);return next}catch{saveSession(null);return null}}
async function me(){if(!session)return null;try{return await api('/auth/v1/user')}catch{if(await refresh())return api('/auth/v1/user');return null}}
async function sendOtp(email){return api('/auth/v1/otp',{method:'POST',auth:false,body:{email:String(email).trim(),create_user:true,gotrue_meta_security:{captcha_token:null}}})}
async function verifyOtp(email,token){const s=await api('/auth/v1/verify',{method:'POST',auth:false,body:{email:String(email).trim(),token:String(token).trim(),type:'email'}});saveSession(s);return s}
async function signOut(){try{if(session)await api('/auth/v1/logout',{method:'POST'})}finally{saveSession(null);renderAccount()}}
function normalizeTheme(t){return ['becoming','space','connection','rest','belonging','change'].includes(t)?t:(t==='relationships'?'connection':'becoming')}
function normalizePiece(p,userId){if(!uuid.test(p.id))p.id=crypto.randomUUID();return{id:p.id,user_id:userId,piece_date:p.date||new Date().toISOString().slice(0,10),theme:normalizeTheme(p.theme),title:String(p.title||'Untitled').slice(0,240),line:String(p.line||''),reflection:String(p.reflection||''),invitation:String(p.invitation||p.question||''),scene_prompt:String(p.scene||''),private_note:String(p.note||''),appearance_feedback:p.look==='Love it'?'love':p.look==='Not for me'?'not_my_taste':null,resonance_feedback:p.fit==='Yes'?'yes':p.fit==='Not really'?'not_really':p.fit==='Different'?'different':null,why_this:{localWhy:p.why||null},generation_context:{kind:p.kind||'study',palette:p.palette||null,medium:p.medium||null,seed:p.seed||null},saved:true};}
async function pushLocal(){const user=await me();if(!user)throw Error('Sign in first.');const bridge=window.InnerworldLocal;if(!bridge)throw Error('Local studio is not ready.');const s=bridge.getState(),p=s.profile||{};
 await api('/rest/v1/iw_profiles?on_conflict=user_id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:{user_id:user.id,display_name:p.name||'',palette:['terracotta','mineral','orchard','ink'].includes(p.palette)?p.palette:'terracotta',medium:['collage','painting','ink'].includes(p.medium)?p.medium:'collage',motifs:Array.isArray(p.motifs)?p.motifs.slice(0,8):[],default_theme:normalizeTheme(p.theme),astrology_enabled:!!p.astrology,onboarding_complete:!!p.name,updated_at:new Date().toISOString()}});
 const all=[...(s.pieces||[])]; if(s.draft&&!all.some(x=>x.id===s.draft.id))all.push(s.draft); if(all.length)await api('/rest/v1/iw_pieces?on_conflict=id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:all.slice(0,400).map(x=>normalizePiece(x,user.id))});
 bridge.replaceState(s); return all.length;
}
async function pullCloud(){const user=await me();if(!user)throw Error('Sign in first.');const [profiles,pieces]=await Promise.all([api('/rest/v1/iw_profiles?select=*&user_id=eq.'+encodeURIComponent(user.id)),api('/rest/v1/iw_pieces?select=*&user_id=eq.'+encodeURIComponent(user.id)+'&order=piece_date.desc,created_at.desc')]);const bridge=window.InnerworldLocal;if(!bridge)throw Error('Local studio is not ready.');const current=bridge.getState();const profile=profiles?.[0];if(profile)current.profile={...(current.profile||{}),name:profile.display_name,palette:profile.palette,medium:profile.medium,motifs:profile.motifs||[],theme:profile.default_theme,astrology:profile.astrology_enabled};current.pieces=(pieces||[]).map(p=>({id:p.id,date:p.piece_date,theme:p.theme,title:p.title,line:p.line,reflection:p.reflection,invitation:p.invitation,scene:p.scene_prompt,note:p.private_note,look:p.appearance_feedback==='love'?'Love it':p.appearance_feedback==='not_my_taste'?'Not for me':null,fit:p.resonance_feedback==='yes'?'Yes':p.resonance_feedback==='not_really'?'Not really':p.resonance_feedback==='different'?'Different':null,image:null,kind:p.generation_context?.kind||'cloud',saved:true}));current.draft=null;await bridge.replaceState(current);return current.pieces.length;}
function dialog(title,html){const m=document.querySelector('#modal'),b=document.querySelector('#modal-body');if(!m||!b)return;b.innerHTML=`<h2 id="modal-title">${esc(title)}</h2>${html}`;m.showModal();}
async function account(){const user=await me();if(!user){dialog('Your INNERWORLD account',`<p>Sign in by email to sync your private collection across devices. Local mode remains available without an account.</p><form id="iw-cloud-email"><label class="field">Email<input name="email" type="email" required autocomplete="email"></label><button class="button primary">Send sign-in code</button><button class="button" type="button" id="iw-cloud-close">Close</button></form>`);document.querySelector('#iw-cloud-close').onclick=()=>document.querySelector('#modal').close();document.querySelector('#iw-cloud-email').onsubmit=async e=>{e.preventDefault();const email=new FormData(e.target).get('email');try{await sendOtp(email);dialog('Check your email',`<p>Enter the one-time code Supabase sent to <strong>${esc(email)}</strong>.</p><form id="iw-cloud-verify"><label class="field">One-time code<input name="token" inputmode="numeric" autocomplete="one-time-code" required></label><button class="button primary">Sign in</button></form>`);document.querySelector('#iw-cloud-verify').onsubmit=async ev=>{ev.preventDefault();try{await verifyOtp(email,new FormData(ev.target).get('token'));document.querySelector('#modal').close();renderAccount();account();}catch(err){alert(err.message)}}}catch(err){alert(err.message)}};return;}
 dialog('Cloud sync',`<p>Signed in as <strong>${esc(user.email||'your account')}</strong>.</p><p>Cloud sync is opt-in. Uploading sends your profile, saved pieces, and private reflections to your Supabase project under row-level security.</p><div class="actions"><button class="primary" id="iw-push">Sync this device to cloud</button><button id="iw-pull">Replace this device from cloud</button><button id="iw-signout">Sign out</button><button id="iw-cloud-close">Close</button></div>`);document.querySelector('#iw-cloud-close').onclick=()=>document.querySelector('#modal').close();document.querySelector('#iw-push').onclick=async()=>{if(!confirm('Upload this device\'s INNERWORLD profile, saved pieces, and private reflections to your private cloud account?'))return;try{const n=await pushLocal();alert(`Synced ${n} piece${n===1?'':'s'} to your account.`)}catch(err){alert(err.message)}};document.querySelector('#iw-pull').onclick=async()=>{if(!confirm('Replace the current local collection with the cloud collection? Export a local backup first if needed.'))return;try{const n=await pullCloud();document.querySelector('#modal').close();alert(`Loaded ${n} cloud piece${n===1?'':'s'}.`)}catch(err){alert(err.message)}};document.querySelector('#iw-signout').onclick=async()=>{await signOut();document.querySelector('#modal').close()};}
async function renderAccount(){let button=document.querySelector('#iw-account');const bar=document.querySelector('.topbar>div');if(!bar)return;if(!button){button=document.createElement('button');button.id='iw-account';button.className='text-button';button.onclick=account;bar.insertBefore(button,bar.querySelector('.avatar'))}const user=await me();button.textContent=user?'Cloud account':'Sign in';button.title=user?'Manage cloud sync':'Sign in for cross-device sync';}
window.InnerworldCloud={sendOtp,verifyOtp,me,pushLocal,pullCloud,signOut,account};window.addEventListener('load',renderAccount);
})();
