/* Deterministic domain model. Taste and emotional fit are independent. */
(function(g){'use strict';
const themes={becoming:['Before you are ready','You are allowed to begin before you become impressive.','What imperfect version could you make today?'],change:['The open window','You can miss something without returning to it.','What would you carry forward?'],belonging:['A place at the table','You do not have to become smaller to belong.','Where can you arrive as you are?'],relationships:['Room for another','Closeness does not require identical positions.','What ritual could make room for both of you?'],boundaries:['A room of your own','Space is something you can make, not only find.','What could you leave unfilled today?'],rest:['Nothing to prove','Not everything unfinished is a failure.','What could be enough for today?']};
const palettes={terracotta:['#b54b31','#e8c39d','#4d5843','#20251e','#f4f0e6'],blue:['#243b53','#5b7894','#c7d6dc','#8b674d','#f4f0e6'],quiet:['#77766e','#b5ab99','#ddd4c4','#555c50','#f7f4ed'],saturated:['#d33d2f','#f2a900','#184d47','#3f3151','#f4efe2']},media=['tactile collage','unusual still-life photography','painterly surfaces','surreal domestic spaces','delicate drawing'];
const scenes={becoming:'An unfinished room, a vermilion chair and a doorway onto a still ocean.',change:'A greenhouse window opens toward a pale horizon. One plant grows beyond a terracotta pot.',belonging:'A long table, mismatched chairs and one deliberately open place.',relationships:'Two different sculptural vessels share a stable table beneath an open sky.',boundaries:'A chair by an open window, with generous distance from a dining table.',rest:'A stone bowl, folded linen and a branch on a sunlit plinth.'};
const own=(o,k)=>Object.hasOwn(o,k),text=(s,n=4000)=>typeof s==='string'?s.slice(0,n):'',escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),uuid=s=>typeof s==='string'&&/^[a-f0-9]{8}-[a-f0-9]{4}-[1-8][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/i.test(s),id=()=>crypto.randomUUID();
const dayKey=(d=new Date())=>[d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');
const validDay=s=>typeof s==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(s)&&Number.isFinite(Date.parse(s))&&new Date(s+'T12:00:00Z').toISOString().slice(0,10)===s;
function hash(s){let n=2166136261;for(const c of String(s)){n^=c.charCodeAt(0);n=Math.imul(n,16777619)}return n>>>0;}
const safeImage=s=>typeof s==='string'&&s.length<=18000000&&/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(s);
function profile(p={}){p=p||{};const b=p.birth||{},t={connection:'relationships',space:'boundaries'}[p.theme]||p.theme,pa={mineral:'blue',orchard:'saturated',ink:'quiet'}[p.palette]||p.palette,m={collage:media[0],painting:media[2],ink:media[4]}[p.medium]||p.medium;return{name:text(p.name,40),theme:own(themes,t)?t:'becoming',palette:own(palettes,pa)?pa:'terracotta',medium:media.includes(m)?m:media[0],motifs:(Array.isArray(p.motifs)?p.motifs:['windows','water']).map(x=>text(x,60)).filter(Boolean).slice(0,8),descriptors:(Array.isArray(p.descriptors)?p.descriptors:[]).map(x=>text(x,60)).filter(Boolean).slice(0,12),experience:text(p.experience),mood:text(p.mood,80),astrology:p.astrology===true,birth:{date:text(b.date||p.birthDate,10),time:text(b.time||p.birthTime,8),timezone:text(b.timezone||p.birthTimezone,80),place:text(b.place,180),lat:Number.isFinite(b.lat)?b.lat:null,lng:Number.isFinite(b.lng)?b.lng:null,disambiguation:['earlier','later'].includes(b.disambiguation)?b.disambiguation:'reject'},references:(Array.isArray(p.references)?p.references:[]).filter(r=>r&&safeImage(r.image)).slice(0,3).map(r=>({id:uuid(r.id)?r.id:id(),image:r.image,imagePath:text(r.imagePath,220)||null,label:text(r.label,80)}))};}
function makePiece(pr={},e={}){const p=profile(pr),t=own(themes,e.theme)?e.theme:p.theme,date=validDay(e.date)?e.date:dayKey(),rev=Number.isSafeInteger(e.revision)?Math.max(0,e.revision):0;return{id:uuid(e.id)?e.id:id(),date,sessionDate:dayKey(),theme:t,seed:hash([date,t,p.palette,e.question||'',rev].join('|')),title:themes[t][0],line:themes[t][1],invitation:themes[t][2],reflection:'A built-in study in '+t+'. You decide what, if anything, it means to you.',scene:scenes[t],question:text(e.question),note:'',look:null,fit:null,image:null,imagePath:null,kind:'study',revision:rev,parentId:uuid(e.parentId)?e.parentId:null,createdAt:new Date().toISOString(),visualProfile:{palette:p.palette,medium:p.medium,motifs:p.motifs,descriptors:p.descriptors},why:'A built-in reflection using your chosen theme and aesthetic. It has not interpreted your words or inferred your emotions.'};}
function normalizePiece(r,pr){if(!r||typeof r!=='object')throw Error('Invalid artwork.');const t={connection:'relationships',space:'boundaries'}[r.theme]||r.theme,p=makePiece(pr,{...r,theme:t}),v=profile(r.visualProfile||pr);return{...p,sessionDate:validDay(r.sessionDate)?r.sessionDate:p.date,title:text(r.title||p.title,160),line:text(r.line||p.line,300),invitation:text(r.invitation||p.invitation,500),reflection:text(r.reflection||p.reflection,3000),scene:text(r.scene||r.visualConcept||p.scene,6000),note:text(r.note,12000),why:text(r.why||p.why,2000),image:safeImage(r.image)?r.image:null,imagePath:text(r.imagePath,220)||null,imageModel:text(r.imageModel,80),kind:['ai','imported'].includes(r.kind)?r.kind:r.image?'ai':'study',look:['Love it','Not for me'].includes(r.look)?r.look:null,fit:['Yes','Not really','Different'].includes(r.fit)?r.fit:null,visualProfile:{palette:v.palette,medium:v.medium,motifs:v.motifs,descriptors:v.descriptors},createdAt:Number.isFinite(Date.parse(r.createdAt))?r.createdAt:p.createdAt};}
function state(raw={}){if(!raw||!Array.isArray(raw.pieces||[])||!Array.isArray(raw.chapters||[])||(raw.pieces||[]).length>400||(raw.chapters||[]).length>100)throw Error('Invalid or oversized studio.');const p=raw.profile?profile(raw.profile):null,map=new Map(),pieces=(raw.pieces||[]).map(r=>{const n=normalizePiece(r,p);map.set(r.id,n.id);return n});if(new Set(pieces.map(x=>x.id)).size!==pieces.length)throw Error('Duplicate artwork IDs.');let draft=raw.draft?normalizePiece(raw.draft,p):null;if(draft&&map.has(raw.draft.id))draft.id=map.get(raw.draft.id);return{app:'the-finer-things',version:6,profile:p,pieces,draft,chapters:(raw.chapters||[]).map(c=>{if(!c||!Array.isArray(c.ids))throw Error('Invalid chapter');return{id:uuid(c.id)?c.id:id(),title:text(c.title,120),description:text(c.description,2000),ids:[...new Set(c.ids.map(x=>map.get(x)||x).filter(x=>pieces.some(p=>p.id===x)))]}}),revision:Number.isSafeInteger(raw.revision)?raw.revision:0,owner:uuid(raw.owner)?raw.owner:null};}
function validateBackup(r){if(r?.app!=='the-finer-things')throw Error('Not a Finer Things backup.');for(const p of [...(r.pieces||[]),...(r.draft?[r.draft]:[])])if(p.image&&!safeImage(p.image))throw Error('Unsafe image in backup.');return state(r);}
function promptFor(p){const v=p.visualProfile;return `${p.scene}\nVisual language: ${v.medium}; ${v.palette} palette; motifs ${v.motifs.join(', ')}; ${v.descriptors?.join(', ')||''}. Tactile, intentional art-school editorial composition. No text, zodiac glyphs, watermarks or cosmic clip art. A metaphor, not a diagnosis.`.slice(0,6000);}
function publicPiece(p){return{title:text(p.title,160),line:text(p.line,300),image:safeImage(p.image)?p.image:null};}
function artSVG(p){const a=palettes[p.visualProfile?.palette]||palettes.terracotta,n=p.seed>>>0,x=150+n%100;return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 720 900"><title>Built-in architectural study</title><defs><filter id="g"><feTurbulence baseFrequency=".7" numOctaves="3" seed="${n%90}"/><feColorMatrix type="saturate" values="0"/></filter></defs><rect width="720" height="900" fill="${a[4]}"/><path d="M0 0H105V640L0 780Z" fill="${a[2]}"/><path d="M105 0H720V640H105Z" fill="${a[1]}"/><rect x="${x}" y="125" width="280" height="455" fill="${a[2]}"/><rect x="${x+20}" y="145" width="240" height="415" fill="${a[4]}"/><path d="M${x+20} 400h240v160h-240Z" fill="${a[2]}"/><path d="M${x+20} 560h240L680 900H120Z" fill="${a[4]}" opacity=".75"/><path d="M165 620h105v25H165ZM170 490h23v260h-23ZM250 505h23v260h-23ZM180 505l80 15v55l-80-15Z" fill="${a[0]}"/><rect width="720" height="900" filter="url(#g)" opacity=".12" style="mix-blend-mode:multiply"/></svg>`;}
g.InnerworldCore={themes,palettes,media,scenes,text,escape,uuid,dayKey,validDay,hash,safeImage,profile,state,makePiece,normalizePiece,promptFor,publicPiece,validateBackup,artSVG};})(globalThis);
