import http from 'node:http';
import {readFile} from 'node:fs/promises';
import {dirname,join} from 'node:path';
import {fileURLToPath} from 'node:url';
import {calculateChart} from './astrology.mjs';
const root=dirname(fileURLToPath(import.meta.url));
const assets=new Map([['/','index.html'],['/index.html','index.html'],['/core.js','core.js'],['/app.js','app.js'],['/cloud.js','cloud.js'],['/style.css','style.css'],['/manifest.webmanifest','manifest.webmanifest'],['/sw.js','sw.js'],['/icon.svg','icon.svg']]);
const types={html:'text/html; charset=utf-8',js:'text/javascript; charset=utf-8',css:'text/css; charset=utf-8',webmanifest:'application/manifest+json',svg:'image/svg+xml'};
export function createStudioServer(o={}){
 const env=o.env||process.env,port=Number(env.PORT||3000),host=env.HOST||'127.0.0.1',origin=env.APP_ORIGIN||`http://127.0.0.1:${port}`,apiKey=env.OPENAI_API_KEY||'',imageModel=env.OPENAI_IMAGE_MODEL||'gpt-image-2',textModel=env.OPENAI_TEXT_MODEL||'gpt-5.6-luna',supabaseUrl=env.SUPABASE_URL||'',supabaseKey=env.SUPABASE_PUBLISHABLE_KEY||'',enabled=env.ENABLE_AI==='1'&&!!apiKey,provider=o.provider||fetch,dailyLimit=Math.max(1,Math.min(100,Number(env.MAX_GENERATIONS_PER_DAY)||10));
 const server=http.createServer(async(req,res)=>{
  const send=(s,d)=>{res.writeHead(s,{'Content-Type':'application/json','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});res.end(JSON.stringify(d))};
  const body=async(max=25000)=>{let size=0,chunks=[];for await(const c of req){size+=c.length;if(size>max)throw Object.assign(new Error('Request too large.'),{status:413});chunks.push(c)}try{return JSON.parse(Buffer.concat(chunks).toString('utf8'))}catch{throw Object.assign(new Error('Invalid JSON.'),{status:400})}};
  const checkOrigin=()=>{if(req.headers.origin&&req.headers.origin!==origin)throw Object.assign(new Error('Origin not permitted.'),{status:403})};
  const requireUser=async()=>{const auth=req.headers.authorization||'';if(!auth.startsWith('Bearer ')||!supabaseUrl||!supabaseKey)throw Object.assign(new Error('Sign in to use this feature.'),{status:401});const r=await provider(`${supabaseUrl}/auth/v1/user`,{headers:{Authorization:auth,apikey:supabaseKey},signal:AbortSignal.timeout(10000)});if(!r.ok)throw Object.assign(new Error('Your session is no longer valid. Sign in again.'),{status:401});const user=await r.json();if(!user?.id)throw Object.assign(new Error('Could not verify this account.'),{status:401});return{user,auth}};
  const consumeQuota=async auth=>{const r=await provider(`${supabaseUrl}/functions/v1/innerworld-quota`,{method:'POST',headers:{Authorization:auth,apikey:supabaseKey,'Content-Type':'application/json'},body:JSON.stringify({limit:dailyLimit}),signal:AbortSignal.timeout(10000)});if(!r.ok)throw Object.assign(new Error('Could not verify generation quota.'),{status:r.status===401?401:503});const q=await r.json();if(!q?.allowed)throw Object.assign(new Error('Daily artwork generation limit reached.'),{status:429});return q};
  try{
   const path=new URL(req.url,origin).pathname;
   if(path==='/api/status')return send(200,{available:enabled,mode:enabled?'account-ai':'study',imageModel:enabled?imageModel:null,textModel:enabled?textModel:null,astrology:true,cloud:true,membership:true,auth:'supabase',durableQuota:true});
   if(path==='/api/astrology'){if(req.method!=='POST')return send(405,{error:'Use POST.'});checkOrigin();await requireUser();const b=await body(5000);if(b.consent!==true||typeof b.birthISO!=='string')return send(400,{error:'Explicit astrology consent and a birth date/time are required.'});return send(200,calculateChart({birthISO:b.birthISO,atISO:b.atISO}))}
   if(path==='/api/interpret'){if(req.method!=='POST')return send(405,{error:'Use POST.'});if(!enabled)return send(503,{error:'AI reflection is not configured on this server.'});checkOrigin();await requireUser();const b=await body(12000);if(b.consent!==true||typeof b.theme!=='string'||typeof b.experience!=='string'||b.experience.length>4000)return send(400,{error:'Approve a valid reflection input.'});const schema={type:'object',additionalProperties:false,properties:{title:{type:'string'},line:{type:'string'},reflection:{type:'string'},invitation:{type:'string'},visual_concept:{type:'string'},why_this:{type:'string'}},required:['title','line','reflection','invitation','visual_concept','why_this']},input={theme:b.theme,experience:b.experience,visual_language:b.visual_language||{},astrology:b.astrology||null};const r=await provider('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:'Bearer '+apiKey,'Content-Type':'application/json'},body:JSON.stringify({model:textModel,store:false,input:[{role:'system',content:[{type:'input_text',text:'You are INNERWORLD, a concise reflective art-journal writing engine. Be observant, non-diagnostic, non-predictive, and never claim hidden knowledge. Astrology, if supplied, is only a symbolic lens and never overrides explicit self-report. Do not equate dark aesthetics with negative emotion. Avoid mystical clichés, fear, commands, therapy language, compatibility verdicts, or certainty about relationships.'}]},{role:'user',content:[{type:'input_text',text:JSON.stringify(input)}]}],text:{format:{type:'json_schema',name:'innerworld_reflection',strict:true,schema}}}),signal:AbortSignal.timeout(60000)});if(!r.ok)return send(502,{error:`Reflection provider returned ${r.status}.`});const j=await r.json(),text=j.output_text||j.output?.flatMap(x=>x.content||[]).find(x=>x.type==='output_text')?.text;if(!text)return send(502,{error:'Reflection provider returned no usable text.'});try{return send(200,JSON.parse(text))}catch{return send(502,{error:'Reflection provider returned invalid structured output.'})}}
   if(path==='/api/generate'){if(req.method!=='POST')return send(405,{error:'Use POST.'});if(!enabled)return send(503,{error:'AI generation is not configured on this server.'});checkOrigin();const {auth}=await requireUser();const b=await body();if(!b?.consent||typeof b.prompt!=='string'||b.prompt.length<10||b.prompt.length>6000)return send(400,{error:'Approve a valid visual prompt.'});const quota=await consumeQuota(auth);const r=await provider('https://api.openai.com/v1/images/generations',{method:'POST',headers:{Authorization:'Bearer '+apiKey,'Content-Type':'application/json'},body:JSON.stringify({model:imageModel,prompt:b.prompt,n:1,size:'1024x1536',quality:'medium',output_format:'png'}),signal:AbortSignal.timeout(150000)});if(!r.ok)return send(502,{error:`Image provider returned ${r.status}. Check model access and billing.`});const j=await r.json(),b64=j.data?.[0]?.b64_json;if(typeof b64!=='string'||!b64.length)return send(502,{error:'Image provider returned no image.'});let bytes;try{bytes=Buffer.from(b64,'base64')}catch{return send(502,{error:'Image provider returned invalid image data.'})}const png=bytes.length>8&&bytes.subarray(0,8).equals(Buffer.from([0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a]));if(!png)return send(502,{error:'Image provider returned a non-PNG payload.'});return send(200,{image:'data:image/png;base64,'+b64,model:imageModel,quota:{used:quota.used,limit:quota.limit_count}})}
   if(!['GET','HEAD'].includes(req.method))return send(405,{error:'Method not allowed.'});const f=assets.get(path);if(!f)return send(404,{error:'Not found.'});const bytes=await readFile(join(root,f));res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob: https://jefhxrtaqzxcijzvzpcy.supabase.co; connect-src 'self' https://jefhxrtaqzxcijzvzpcy.supabase.co; object-src 'none'; base-uri 'none'; frame-ancestors 'none'; form-action 'self' https://buy.stripe.com");res.writeHead(200,{'Content-Type':types[f.split('.').pop()]||'application/octet-stream','Cache-Control':'no-cache','Referrer-Policy':'no-referrer','X-Frame-Options':'DENY'});res.end(req.method==='HEAD'?undefined:bytes)
  }catch(e){if(!res.headersSent)send(e.status||500,{error:e.status?e.message:'Server could not complete the request.'});else res.end()}
 });server.requestTimeout=170000;server.headersTimeout=15000;return{server,port,host}
}
if(process.argv[1]===fileURLToPath(import.meta.url)){const{server,port,host}=createStudioServer();server.listen(port,host,()=>console.log(`Innerworld: http://${host}:${port}`))}
