/* IndexedDB with optional passphrase encryption and stale-tab protection. */
(function(g){'use strict';let db,revision=0,key=null,salt=null,queue=Promise.resolve();const enc=new TextEncoder(),dec=new TextDecoder();
function read(){return new Promise((y,n)=>{const q=db.transaction('vault').objectStore('vault').get('studio');q.onsuccess=()=>{revision=q.result?.revision||0;y(q.result||null)};q.onerror=()=>n(q.error)});}
async function open(){db=await new Promise((y,n)=>{const q=indexedDB.open('innerworld-release-060',1);q.onupgradeneeded=()=>q.result.createObjectStore('vault');q.onsuccess=()=>y(q.result);q.onerror=()=>n(q.error)});return read();}
async function derive(password,s){const m=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt:s,iterations:310000,hash:'SHA-256'},m,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);}
async function unlock(password){const e=await read(),k=await derive(password,e.salt);let d;try{d=JSON.parse(dec.decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:e.iv},k,e.payload)))}catch{throw Error('Incorrect passphrase.')}key=k;salt=e.salt;return d;}
function save(document){const copy=structuredClone(document);queue=queue.catch(()=>{}).then(async()=>{let e={document:copy,encrypted:false};if(key){const iv=crypto.getRandomValues(new Uint8Array(12));e={encrypted:true,iv,salt,payload:await crypto.subtle.encrypt({name:'AES-GCM',iv},key,enc.encode(JSON.stringify(copy)))}}return new Promise((y,n)=>{const tx=db.transaction('vault','readwrite'),s=tx.objectStore('vault'),q=s.get('studio');let stale=false;q.onsuccess=()=>{if((q.result?.revision||0)!==revision){stale=true;tx.abort();return}s.put({...e,revision:revision+1},'studio')};tx.oncomplete=()=>{revision++;y(revision)};tx.onabort=()=>n(Error(stale?'Another tab saved newer changes. Export a backup, then reload.':'Storage could not save. Export a backup before closing.'));tx.onerror=()=>n(tx.error)});});return queue;}
async function encrypt(p,doc){if(p.length<12)throw Error('Use at least 12 characters.');const old={key,salt};salt=crypto.getRandomValues(new Uint8Array(16));key=await derive(p,salt);try{await save(doc)}catch(e){key=old.key;salt=old.salt;throw e;}}
async function erase(){await queue.catch(()=>{});await new Promise((y,n)=>{const tx=db.transaction('vault','readwrite');tx.objectStore('vault').clear();tx.oncomplete=y;tx.onerror=()=>n(tx.error)});revision=0;key=null;salt=null;for(const v of [3,4,5])localStorage.removeItem('finer-things-innerworld-v'+v);}
g.IWStorage={open,save,unlock,encrypt,erase,encrypted:()=>!!key};})(globalThis);
